//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI_V_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.FacturaDetalles = new HashSet<FacturaDetalle>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdTipo { get; set; }
        public Nullable<decimal> Total_Facturado { get; set; }
        public Nullable<decimal> Total_Pagado { get; set; }
        public Nullable<decimal> Total_Descuento { get; set; }
        public Nullable<decimal> Fecha_Facturacion { get; set; }
        public Nullable<decimal> Fecha_Vencimiento { get; set; }
        public string Tipo { get; set; }
    
        public virtual Contacto Contacto { get; set; }
        public virtual TipoFactura TipoFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaDetalle> FacturaDetalles { get; set; }
    }
}
