//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI_V_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaDetalle
    {
        public int Id { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public Nullable<int> IdArticulo { get; set; }
        public string Decripcion { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Cantida { get; set; }
    
        public virtual Factura Factura { get; set; }
    }
}
