//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI_V_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materiale
    {
        public string DESCRIPCION { get; set; }
        public string UND { get; set; }
        public string PU_ITBIS { get; set; }
        public string PU_SIN_ITBIS { get; set; }
        public string RENDIMIENTOS_OBS { get; set; }
        public string SUPLIDOR_RECOMENDADO { get; set; }
        public int ID { get; set; }
        public Nullable<int> Padre { get; set; }
    }
}
