//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI_V_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int Id { get; set; }
        public Nullable<int> IDAlmacen { get; set; }
        public Nullable<int> IDCategoria { get; set; }
        public Nullable<int> IDUnidad { get; set; }
        public string Producto1 { get; set; }
        public Nullable<decimal> Precio_Compra { get; set; }
        public Nullable<decimal> Precio_Venta { get; set; }
        public Nullable<int> Stock { get; set; }
        public string CodigoBarra { get; set; }
        public Nullable<decimal> Precio_SinITBIS { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }
    }
}
