//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI_V_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recibo
    {
        public int Id { get; set; }
        public Nullable<int> IDFactura { get; set; }
        public Nullable<decimal> Pagado { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdMetodoPago { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual MetodoPago MetodoPago { get; set; }
    }
}
